// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQcNsqPRqm7AwWSuA4zCBaNU6L-eeqJFk',
    appId: '1:677836265980:web:3104d79f9d7d7d24c6fa79',
    messagingSenderId: '677836265980',
    projectId: 'wordleappdatabase',
    authDomain: 'wordleappdatabase.firebaseapp.com',
    storageBucket: 'wordleappdatabase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM8YZam0UI2O2folsMjYPTG1dAJnY0sRo',
    appId: '1:677836265980:android:8f2df676a108fca7c6fa79',
    messagingSenderId: '677836265980',
    projectId: 'wordleappdatabase',
    storageBucket: 'wordleappdatabase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxaLZV1Z6zEeYcgJUOSxFfE25duCOPBJQ',
    appId: '1:677836265980:ios:a11593ccc2a02cddc6fa79',
    messagingSenderId: '677836265980',
    projectId: 'wordleappdatabase',
    storageBucket: 'wordleappdatabase.appspot.com',
    iosBundleId: 'com.example.yazlab2p2v1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxaLZV1Z6zEeYcgJUOSxFfE25duCOPBJQ',
    appId: '1:677836265980:ios:a11593ccc2a02cddc6fa79',
    messagingSenderId: '677836265980',
    projectId: 'wordleappdatabase',
    storageBucket: 'wordleappdatabase.appspot.com',
    iosBundleId: 'com.example.yazlab2p2v1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQcNsqPRqm7AwWSuA4zCBaNU6L-eeqJFk',
    appId: '1:677836265980:web:cf31fb8aee8e19cdc6fa79',
    messagingSenderId: '677836265980',
    projectId: 'wordleappdatabase',
    authDomain: 'wordleappdatabase.firebaseapp.com',
    storageBucket: 'wordleappdatabase.appspot.com',
  );
}
